name: Install Kong Deck CLI
description: Install Kong Gateway CLI Deck
inputs:
  version:
    description: Kong Deck CLI Version to install
    required: true
runs:
  using: composite
  steps:
    - run: |
        curl -sL https://github.com/kong/deck/releases/download/v${{ inputs.version }}/deck_${{ inputs.version }}_linux_amd64.tar.gz -o deck.tar.gz
        tar -xf deck.tar.gz -C /tmp
        sudo mv /tmp/deck /usr/bin/deck
      shell: bash
